#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

### Helper func
is_board_type() {
    local board releasefile
    board=""
    releasefile="/etc/armbian-release"
    if [[ -f "${releasefile}" ]]; then
        board="$(grep "BOARD=" "${releasefile}" | cut -d'=' -f2)"
    fi
    echo "${board}"
}

echo_green "Apply SmartPad specific patches..."
unpack /filesystem/root /
if [[ -f /etc/X11/xorg.conf.d/03-smartpad-rotate-touch.conf ]]; then
    rm -fv /etc/X11/xorg.conf.d/03-smartpad-rotate-touch.conf
fi

echo_green "Apply SmartPad specific patches... [DONE]"


### Enable Serial and SPI connections by default
if [[ "$(is_board_type)" == "smartpad" ]]; then
    echo_green "Enable Serial and SPI interface on SmartPad..."
    echo "overlays=spi-spidev uart1 uart2" >> "${SMARTPAD_CONFIG_TXT_FILE}"
    echo "param_spidev_spi_bus=1" >> "${SMARTPAD_CONFIG_TXT_FILE}"
    echo_green "Enable Serial and SPI interface on SmartPad... DONE!"
fi

### Install plymouth theme and install yumi Plymouth repository
echo_green "Install Yumi Lab Plymouth theme on SmartPad..."

smartpad_install_theme() {
    local src dest
    dest="/usr/share/plymouth/themes/"
    src="/home/${BASE_USER}/$(basename "${SMARTPAD_PLYMOUTH_REPO/.git/}")"
    src="${src}/pack_3/pixels"
    if [[ -d "${src}" ]]; then
        sudo cp -vr "${src}" "${dest}"
    fi
    echo_green "Set default theme to ${SMARTPAD_PLYMOUTH_THEME} ..."
    sudo plymouth-set-default-theme "${SMARTPAD_PLYMOUTH_THEME}"
}

pushd "/home/${BASE_USER}" &>/dev/null
sudo -u "${BASE_USER}" git clone "${SMARTPAD_PLYMOUTH_REPO}"
smartpad_install_theme
popd &>/dev/null

echo_green "Install Yumi Lab Plymouth theme on SmartPad... [DONE]"


echo_green "Install Retropie..."
git clone https://github.com/Yumi-Lab/Retropie-smartpi.git
cd Retropie-smartpi
./install.sh
echo_green "Install Retropie...(DONE)"


echo_green "Change name Retropie..."
# Nouveau nom d'hôte
"${NEW_HOSTNAME}"="smartpiretro"
# Modifier le fichier /etc/hostname
echo "${NEW_HOSTNAME}" | sudo tee /etc/hostname
# Modifier le fichier /etc/hosts
sudo sed -i "s/$(hostname)/"${NEW_HOSTNAME}"/g" /etc/hosts
echo_green "Change name Retropie...(DONE)"

echo_green "Install filebrowser..."
sudo curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash 
sudo filebrowser -r /root/RetroPie/
authauriser les ip sinon par défaut juste local
filebrowser -d filebrowser.db config set --address 0.0.0.0
# Créer le script bash pour démarrer FileBrowser avec les commandes nécessaires
cat << 'EOF' > /usr/local/bin/start_filebrowser.sh
#!/bin/bash
filebrowser -d filebrowser.db config set --address 0.0.0.0
filebrowser -r /root/RetroPie/
EOF
# Rendre le script exécutable
chmod +x /usr/local/bin/start_filebrowser.sh
# Créer le fichier de service systemd
cat << 'EOF' > /etc/systemd/system/filebrowser.service
[Unit]
Description=FileBrowser Service
After=network.target

[Service]
ExecStart=/usr/local/bin/start_filebrowser.sh
Restart=always
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF
# Recharger les services systemd pour prendre en compte le nouveau fichier de service
systemctl daemon-reload
# Activer le service pour qu'il démarre automatiquement au démarrage du système
systemctl enable filebrowser.service
# Démarrer le service immédiatement
systemctl start filebrowser.service
# Afficher l'état du service
systemctl status filebrowser.service
echo_green "Install filebrowser...(DONE)"

echo_green "Install menu emulastation..."
unpack /filesystem/root/RetroPie /
echo_green "Install menu emulastation...(DONE)"